version: '3.8'

services:
  # Backend Service (Hono.js API)
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: tamagotchi_backend
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/db
      - APP_URL=http://localhost:3000
      - SECRET_KEY=ZON7hTBZiO0St7rTZjgp
      - BACKEND_PORT=5000
    ports:
      - '5000:5000'
    depends_on:
      - db
      - redis
    networks:
      - backend

  # Nginx for Proxying (Frontend + Backend)
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./apps/mini-app/build:/usr/share/nginx/html:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - '80:80'
      - '443:443'
    environment:
      - NGINX_HOST=game.pixelenc.ru
    depends_on:
      - backend
    networks:
      - backend # Add nginx to the backend network

  # Certbot for ssl
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email daniel.kasatkin.work@gmail.com -d game.pixelenc.ru --agree-tos

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  # Redis Cache
  redis:
    image: redis
    container_name: redis_cache
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db-data:
