version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - db-data:/var/lib/postgresql/data
    network_mode: host

  redis:
    network_mode: host
    image: redis
volumes:
  db-data:
