version: '3.8'

services:
  # Frontend Service (Vite + Nginx)
  frontend:
    build:
      context: .
      dockerfile: apps/mini-app/Dockerfile
    container_name: tamagotchi_frontend
    environment:
      - VITE_API_URL=http://backend:3000
    ports:
      - '5173:5173'
    networks:
      - backend
      - frontend

  # Backend Service (Hono.js API)
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: tamagotchi_backend
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/db
      - BACKEND_PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECRET_KEY=random
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    networks:
      - backend

  # Nginx for Proxying (Frontend + Backend)
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html:ro
    ports:
      - '80:80'
      - '443:443'
    environment:
      - NGINX_HOST=game.pixelenc.ru
    depends_on:
      - frontend
      - backend
    networks:
      - frontend

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  # Redis Cache
  redis:
    image: redis
    container_name: redis_cache
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db-data:
