version: '3.8'

services:
  # Backend Service (Hono.js API)
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: tamagotchi_backend
    ports:
      - '5000:5000'
    depends_on:
      - db
      - redis
    networks:
      - backend

  # Nginx for Proxying (Frontend + Backend)
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./apps/mini-app/build:/usr/share/nginx/html:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - '80:80'
      - '443:443'
    environment:
      - NGINX_HOST=game.pixelenc.ru
    depends_on:
      - backend
    networks:
      - backend # Add nginx to the backend network

  # Certbot for ssl
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email daniel.kasatkin.work@gmail.com -d game.pixelenc.ru --agree-tos

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'True'
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - '8080:8080'
    expose:
      - 8080
    restart: always
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  # Redis Cache
  redis:
    image: redis
    container_name: redis_cache
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db-data:
  pgadmin-data:
