# Backend API Dockerfile
FROM node:18 AS build

WORKDIR /app

# Install dependencies
COPY api/package*.json ./
RUN npm install --production

# Copy source code
COPY api .

# Build the API
RUN npm run build

# Set up for production
FROM node:18

WORKDIR /app

# Install production dependencies
COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/dist /app/dist

EXPOSE 3000

CMD ["node", "./dist/index.js"]
